[tool.black]
line-length = 88
target-version = ["py310"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
skip = ["venv", "__pycache__", "migrations", "build", "dist"]