"""Initial migration

Revision ID: 2f5fab3186f4
Revises: 
Create Date: 2025-12-30 18:16:35.210160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f5fab3186f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minigames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('minigame_number', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='minigamenumber'), nullable=False),
    sa.Column('attempted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('minigame_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('test_sessions', 'score')
    op.drop_column('test_sessions', 'taken_language_test')
    op.drop_column('test_sessions', 'taken_visual_test')
    op.drop_column('test_sessions', 'taken_auditory_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sessions', sa.Column('taken_auditory_test', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('test_sessions', sa.Column('taken_visual_test', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('test_sessions', sa.Column('taken_language_test', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('test_sessions', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_table('minigames')
    # ### end Alembic commands ###
