"""open 3 rows in test session

Revision ID: 8c4c84dd8c1e
Revises: 2f5fab3186f4
Create Date: 2025-12-30 18:24:10.710019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4c84dd8c1e'
down_revision: Union[str, Sequence[str], None] = '2f5fab3186f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('test_sessions', sa.Column('taken_auditory_test', sa.Boolean(), nullable=True))
    op.add_column('test_sessions', sa.Column('taken_visual_test', sa.Boolean(), nullable=True))
    op.add_column('test_sessions', sa.Column('taken_language_test', sa.Boolean(), nullable=True))
    
    # Update existing rows with default value
    op.execute("UPDATE test_sessions SET taken_auditory_test = FALSE WHERE taken_auditory_test IS NULL")
    op.execute("UPDATE test_sessions SET taken_visual_test = FALSE WHERE taken_visual_test IS NULL")
    op.execute("UPDATE test_sessions SET taken_language_test = FALSE WHERE taken_language_test IS NULL")
    
    # Now make columns NOT NULL
    op.alter_column('test_sessions', 'taken_auditory_test', nullable=False)
    op.alter_column('test_sessions', 'taken_visual_test', nullable=False)
    op.alter_column('test_sessions', 'taken_language_test', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_sessions', 'taken_language_test')
    op.drop_column('test_sessions', 'taken_visual_test')
    op.drop_column('test_sessions', 'taken_auditory_test')
    # ### end Alembic commands ###
