from enum import StrEnum

class QuestionType(StrEnum):
    PHONEMIC_AWARENESS_1 = "PHONEMIC_AWARENESS_1"
    PHONEMIC_AWARENESS_2 = "PHONEMIC_AWARENESS_2"
    LETTER_RECOGNITION_1 = "LETTER_RECOGNITION_1"
    LETTER_RECOGNITION_2 = "LETTER_RECOGNITION_2"
    READING_COMPREHENSION_1 = "READING_COMPREHENSION_1"
    READING_COMPREHENSION_2 = "READING_COMPREHENSION_2"
    SPELLING_AND_WRITING_1 = "SPELLING_AND_WRITING_1"
    SPELLING_AND_WRITING_2 = "SPELLING_AND_WRITING_2"
    LANGUAGE_UNDERSTANDING_AND_RECOGNITION_1 = "LANGUAGE_UNDERSTANDING_AND_RECOGNITION_1"
    LANGUAGE_UNDERSTANDING_AND_RECOGNITION_2 = "LANGUAGE_UNDERSTANDING_AND_RECOGNITION_2"

class PredictDyslexia(StrEnum):
    YES = "YES"
    NO = "NO"
    MAYBE = "MAYBE"

class TestStatus(StrEnum):
    COMPLETED = "COMPLETED"
    IN_PROGRESS = "IN_PROGRESS"
    
class TestDifficulty(StrEnum):
    BASIC = "BASIC"
    ADVANCED = "ADVANCED"
    
class ProfileType(StrEnum):
    PARENT = 'PARENT'
    CHILD = 'CHILD'
    
class Gender(StrEnum):
    MALE = 'MALE'
    FEMALE = 'FEMALE'